"""add archived and tags to conversations

Revision ID: 5c906286dcba
Revises:
Create Date: 2026-04-14 13:57:03.000898

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c906286dcba"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("archived", sa.Boolean(), nullable=False, server_default="0"))
    op.add_column("conversations", sa.Column("tags", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "tags")
    op.drop_column("conversations", "archived")
    # ### end Alembic commands ###
