"""add conversation_summary and user_pattern tables

Revision ID: 7ab819dfa573
Revises: 5c906286dcba
Create Date: 2026-04-29 11:32:40.297351

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ab819dfa573"
down_revision: str | Sequence[str] | None = "5c906286dcba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_patterns",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("table_name", sa.String(length=100), nullable=True),
        sa.Column("pattern_type", sa.String(length=50), nullable=True),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("last_used", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversation_summaries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("key_sql", sa.Text(), nullable=True),
        sa.Column("key_topics", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conversation_summaries")
    op.drop_table("user_patterns")
    # ### end Alembic commands ###
