"""add_db_connection_credentials_and_driver

Revision ID: 9d3003585296
Revises: 7ab819dfa573
Create Date: 2026-05-07 14:01:05.554294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3003585296'
down_revision: Union[str, Sequence[str], None] = '7ab819dfa573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_connections', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('db_connections', sa.Column('password', sa.Text(), nullable=True))
    op.add_column('db_connections', sa.Column('driver_type', sa.String(length=20), nullable=True))
    op.add_column('db_connections', sa.Column('connection_tested', sa.Boolean(), nullable=True))
    op.add_column('db_connections', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    # 给现有数据设置默认值
    op.execute("UPDATE db_connections SET driver_type = 'manual', connection_tested = 0 WHERE driver_type IS NULL")
    # 然后设为 NOT NULL
    with op.batch_alter_table('db_connections') as batch_op:
        batch_op.alter_column('driver_type', nullable=False)
        batch_op.alter_column('connection_tested', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_connections', 'last_synced_at')
    op.drop_column('db_connections', 'connection_tested')
    op.drop_column('db_connections', 'driver_type')
    op.drop_column('db_connections', 'password')
    op.drop_column('db_connections', 'username')
    # ### end Alembic commands ###
